### ISSUE TITLE
Opens on wrong display

### ISSUE THREAD

**Issue by Minos42** [rojarsmith/TrayToolbar#11]
Since a while if i open the TrayToolbar by clicking on the icon in the taskbar on display a, it opens the context menu on display b.
Exiting and reopening the application doesn't fix this behaviour.
![2022-09-27 10_16_58-](https://user-images.githubusercontent.com/114474631/192472333-e0080f4d-23d2-48b6-b3c2-8f657fe18fce.png)

**Comment by rojarsmith** [comment]
Thanks, let me check this.

**Comment by rojarsmith** [comment]
Ok, the bug of different resoltion at multi monitor environment.

Maybe fix at next version.
