### ISSUE TITLE
Shortcuts - remove .lnk extension

### ISSUE THREAD

**Issue by ope-nz** [rojarsmith/TrayToolbar#12]
Hi, thanks for the great tool.

![image](https://user-images.githubusercontent.com/26259049/193485486-66dd6f91-781b-44f8-bc7e-afdb5e13500b.png)

Not a big deal but shortcuts display the .lnk extension. The extension should be hidden.

**Comment by rojarsmith** [comment]
Thanks. I will add to check list.

I'm sorry I've been busy at work lately.

**Comment by rojarsmith** [comment]
Need new feature. Maybe next verstion.
