### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by xantari** [rojarsmith/TrayToolbar#5]
This appeared to be open source but I can't find the source.

Unsure if this is malware or not without checking source.

**Comment by rojarsmith** [comment]
This is not open source at this time.

You can use free anti virous software to scan.

**Comment by troymaclure** [comment]
It's funny because I once found a nirsoft binary in one of the app distributed on "The Windows Club". And nirsoft is obviously a malware cesspool.

**Comment by troymaclure** [comment]
Beside, if there is not source, it should not be hosted on an organisation dedicated to the promotion of open source.
