### ISSUE TITLE
Running bat files doesn't show the console window

### ISSUE THREAD

**Issue by filippobottega** [rojarsmith/TrayToolbar#6]
Hello,
  I'm using Windows 11, if I try to run a bat file or a try to run a cmd prompt, the console window doesn't appear even if the process is running. I'm using Process Explorer to check what appens:

![image](https://user-images.githubusercontent.com/2587684/141960134-a1b20bd4-7a25-47d9-9a7e-bba3cf6acefa.png)

  Regards,
    Filippo.

**Comment by filippobottega** [comment]
Solution: 
  TrayToolbar run this command:

`"cmd.exe" /c "MyPath\My link.lnk"`

  Probably the cmd.exe is hidden and has not any visible window.
  To run a command from TrayToolbar you have to write a bat file, for example `CommandPrompt.bat`, containing this command:

`start "Command Prompt" "%windir%\system32\cmd.exe"`

  Using start it is possible to display a new window even if the first cmd.exe process is hidden.

  Regards,
    Filippo.

**Comment by rojarsmith** [comment]
I will pay attention.
