### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by Zaxxon709** [rojarsmith/TrayToolbar#8]
Good day, Just want to thank you for this app. It's what I was looking for since upgrading to Windows 11.

How can I easily change the icon to one suited more for my needs? Thank you

**Comment by rojarsmith** [comment]
Thanks for using. You mean how to change the tray icon ?

**Comment by Zaxxon709** [comment]
> Thanks for using. You mean how to change the tray icon ?

Yes, i wanted to change the folder icon to another.

**Comment by rojarsmith** [comment]
I will seriously consider this feature in the next version. :)

**Comment by Zaxxon709** [comment]
> I will seriously consider this feature in the next version. :)

That would be great...thank you very much
